export const MOCK_PRODUCTS = [
  {
    id: "1",
    name: "Gree GS-18XPUV32 1.5 Ton Inverter Split Type Air Conditioner",
    brand: "Gree",
    price: 58900,
    originalPrice: 75000,
    rating: 4.8,
    reviews: 120,
    image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Group Deal", "Free Shipping", "Free Installation"],
    category: "Air Conditioner",
    isNew: true,
  },
  {
    id: "2",
    name: "Samsung 55\" Crystal 4K UHD Smart TV (CU7700)",
    brand: "Samsung",
    price: 65000,
    originalPrice: 80000,
    rating: 4.9,
    reviews: 85,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Free Shipping", "Express Delivery"],
    category: "TV & Audio",
    isNew: false,
  },
  {
    id: "3",
    name: "LG 320L Top Mount Refrigerator with Smart Inverter",
    brand: "LG",
    price: 45000,
    originalPrice: 52000,
    rating: 4.7,
    reviews: 64,
    image: "https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Free Installation"],
    category: "Home Appliances",
    isNew: true,
  },
  {
    id: "4",
    name: "Philips Essential Airfryer HD9252/90",
    brand: "Philips",
    price: 12500,
    originalPrice: 15000,
    rating: 4.9,
    reviews: 210,
    image: "https://images.unsplash.com/photo-1628840042765-356cda07504e?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Trending", "Free Shipping"],
    category: "Kitchen Appliances",
    isNew: false,
  },
  {
    id: "5",
    name: "Haier 1.0 Ton Non-Inverter AC",
    brand: "Haier",
    price: 38000,
    originalPrice: 42000,
    rating: 4.5,
    reviews: 45,
    image: "https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Group Deal", "Free Installation"],
    category: "Air Conditioner",
    isNew: false,
  },
  {
    id: "6",
    name: "Sony Bravia 65\" 4K Ultra HD Smart LED TV",
    brand: "Sony",
    price: 85000,
    originalPrice: 105000,
    rating: 4.8,
    reviews: 92,
    image: "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Free Shipping"],
    category: "TV & Audio",
    isNew: true,
  },
  {
    id: "7",
    name: "Panasonic Daily Mixer Grinder 3 Jars",
    brand: "Panasonic",
    price: 6500,
    originalPrice: 8000,
    rating: 4.6,
    reviews: 156,
    image: "https://images.unsplash.com/photo-1585515320310-259814833e62?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Free Shipping"],
    category: "Kitchen Appliances",
    isNew: false,
  },
  {
    id: "8",
    name: "Whirlpool Front Load Washing Machine 7.5kg",
    brand: "Whirlpool",
    price: 32000,
    originalPrice: 38000,
    rating: 4.7,
    reviews: 78,
    image: "https://images.unsplash.com/photo-1626806787461-102c1bfaaea1?auto=format&fit=crop&q=80&w=400&h=300",
    tags: ["Group Deal", "Free Installation"],
    category: "Home Appliances",
    isNew: true,
  }
];

export const CATEGORIES = [
  { name: "Air Conditioner", icon: "Wind" },
  { name: "Air Fryer", icon: "Flame" },
  { name: "Blender & Juicer", icon: "Coffee" },
  { name: "Chest Freezer", icon: "Snowflake" },
  { name: "Cooler & Fan", icon: "Fan" },
  { name: "Electric Kettle", icon: "CupSoda" },
  { name: "FHD Google TV", icon: "Tv" },
  { name: "Inverter AC", icon: "Thermometer" },
  { name: "Iron", icon: "Shirt" },
  { name: "Microwave Oven", icon: "Microwave" },
  { name: "Oven & Hob", icon: "ChefHat" },
  { name: "QLED Google TV", icon: "MonitorPlay" },
  { name: "Refrigerator", icon: "Refrigerator" },
  { name: "Rice Cooker", icon: "CookingPot" },
  { name: "TV", icon: "Tv" },
  { name: "Washing Machine", icon: "WashingMachine" },
];
